
.travis.yml:
  simplecov: true

spec/spec_helper.rb:
  coverage_report: true
  mock_with: ':rspec'

Gemfile:
  required:
    ':development':
      - gem: 'puppet-blacksmith'
      - gem: 'github_changelog_generator'
