name: PDK

on:
  - 'push'
  - 'pull_request'

jobs:
  validate:
    runs-on: ubuntu-latest
    container: puppet/pdk:latest
    outputs:
        puppet_unit_test_matrix: ${{ steps.get-outputs.outputs.puppet_unit_test_matrix }}
        github_action_test_matrix: ${{ steps.get-outputs.outputs.github_action_test_matrix }}
    steps:
      - name: Install build-essential
        run: |
          export DEBIAN_FRONTEND=noninteractive;
          apt-get --yes update 
          apt-get --yes install build-essential
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run pdk validate
        run: pdk validate

  unit-test:
    runs-on: ubuntu-latest
    container: puppet/pdk:latest
    steps:
      - name: Install build-essential
        run: |
          export DEBIAN_FRONTEND=noninteractive;
          apt-get --yes update 
          apt-get --yes install build-essential
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run pdk test unit
        run: pdk test unit 
